baseURL = "http://callim105.github.io/"
languageCode = "en-us"
title = "Christian's Dev Blog"
theme = "cactus"

[params]
colortheme = "dark"
mainSectionTitle = "Blog"
mainSection = "posts"
description = "Welcome to my brain dump. Technical musings and miscellaneous thoughts."
staticDir = ['static']
tagsOverview = true


# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

# syntax highlighting
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
